"""uuid, short_code generate before insert

Revision ID: 3c2412f9fb30
Revises: d1f4864f0e62
Create Date: 2024-09-06 10:19:39.722988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2412f9fb30'
down_revision: Union[str, None] = 'd1f4864f0e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_urls_uuid', table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('short_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('visit_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_index('ix_urls_uuid', 'urls', ['uuid'], unique=1)
    # ### end Alembic commands ###
